---
title: "Team"
editor: visual
page-layout: full
toc: false
format:
  html: default
  #docx: default
fontsize: 1.5em
---

### Laurent Gatto, PhD

Laurent Gatto is the head of the CBIO group at UCLouvain and teaches bioinformatics in the Faculty of Pharmacy and Biomedical Sciences (FASB).

[CBIO's webpage](https://lgatto.github.io/cbio-lab/ "CBIO lab")

\

### Sébastien Jodogne, PhD

Sébastien Jodogne is Professor of Computer Science applied to Life Sciences at UCLouvain. An expert in e-Health, he is particularly active in the fields of medical imaging, image analysis and patient education.

[Sébastien Jodogne's webpage](https://www.info.ucl.ac.be/~sjodogne/ "Sébastien Jodogne")

\

### Jérôme Linden, PhD

Jérôme Linden is e-Omix’ project manager and is experienced with data analysis and omics technologies applied to neuroscience. 

\

### Loïc Guille, MSc

Loïc Guille is a bioinformatics research engineer, specialized in the analysis and visualization of single-cell RNA sequencing. 

\

### Axelle Loriot, PhD

Axelle Loriot is a senior researcher in the field of transcriptomics and epigenomics, and is e-Omix's consulting expert.


